name: IMD Daily Rainfall Archive

on:
  schedule:
    - cron: "0 6 * * *"

  workflow_dispatch:
permissions:
  contents: write

jobs:
  archive:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Downloader
        run: |
          python downloader.py